[target.'cfg(all(target_arch = "arm", target_os = "none"))']

runner = "probe-rs run --chip RP2040 --speed 10000"


rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "no-vectorize-loops",
]

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
