[package]
name = "encoder-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
postcard = { workspace = true }
cobs = { workspace = true }
crc = { workspace = true }

[features]
default = []
std = []
